# Config file 

simpletracking:
  target_classes: ["scanner", "rag", 'plastic-bag']
  roi: [[475, 294, 635, 404], [701, 320, 840, 502]]   # Optionnal (leave None : ROI=Full frame)
  frame_skip: 0
  resize: None   # Optionnal
  movement_threshold: 0.01
  smoothing_window: 25
  alpha: 0.8
  min_movement_count: 7
  movement_window: 9
  display_scale: 0.5

detector:
  model_path: "models/final_best.pt"
  conf_threshold: 0.35  
  device: 'cpu'

verdict:
  min_duration: 0.5
  self.min_movement_count: 1

img_size: 416

persistentwatcher:
  background_frame_path: "utils/backgrounds/background_pdv14.jpg"
  model_path: "models/final_best.pt"
  conf_threshold: 0.35  
  device: 'cpu'
  target_classes:
    - plastic-bag
    - products
    - rag
  roi: [514, 296, 611, 357]      
  time_threshold: 1.0
  smoothing_window: 7
  alpha: 0.8
  display_scale: 0.5
  motion_threshold: 0.1       
  disappearance_window: 10
  background_frame_index: 0
  window_size: 7
  min_area_ratio: 0.20
  min_high_frames: 6
  min_low_frames: 3
  min_immobility_duration: 1.5
  high_similarity_threshold: 0.9
  low_similarity_threshold: 0.7
  min_class_count: 4
  roi_threshold: 0.3