# Config file 

simpletracking:
  video_path: "videos/video_CarrefourSP_TBE1_20250916T195008_15.mp4"
  target_classes: ["scanner", "rag", 'plastic-bag']
  roi: [[474, 238, 714, 386], [710, 248, 865, 469]]   # Optionnal (leave None : ROI=Full frame)
  frame_skip: 0
  resize: None   # Optionnal
  movement_threshold: 0.01
  smoothing_window: 25
  alpha: 0.8
  min_movement_count: 7
  movement_window: 9
  display_scale: 0.5

detector:
  model_path: "models/final_best_103.pt"
  conf_threshold: 0.35  
  device: 'cpu'

verdict:
  min_duration: 0.5
  self.min_movement_count: 1


persistentwatcher:
  model_path: "models/final_best_103.pt"
  conf_threshold: 0.35  
  device: 'cpu'
  target_classes:
    - plastic-bag
    - products
    - scanner
    - rag
  roi: [526, 234, 644, 298]
  time_threshold: 1.0
  smoothing_window: 7
  alpha: 0.8
  display_scale: 0.5
  motion_threshold: 0.1       
  disappearance_window: 10
  background_frame_index: 0
  window_size: 7
  min_area_ratio: 0.20
  min_high_frames: 6
  min_low_frames: 3
  min_immobility_duration: 1.5
  high_similarity_threshold: 0.9
  low_similarity_threshold: 0.7