# Config file 


img_size: 416
class_colors:
  scanner: [255, 0, 0]
  hand: [0, 255, 0]
  rag: [0, 0, 255]
  plastic-bag: [255, 255, 0]
  products: [0, 255, 255]
  price-sheets: [255, 0, 255]


simpletracking:
  target_classes: ["scanner", "rag", 'plastic-bag']
  roi:  [[0.5140625, 0.24583333333333332, 0.6578125, 0.4097222222222222],[0.3703125, 0.21944444444444444, 0.4953125, 0.4652777777777778]]   # Optionnal (leave None : ROI=Full frame)
  frame_skip: 1
  resize: None   # Optionnal
  movement_threshold: 0.005
  smoothing_window: 50
  alpha: 1
  min_movement_count: 3
  movement_window: 10
  display_scale: 0.5
  

detector:
  model_path: "models/final_best_103.pt"
  conf_threshold: 0.35  
  device: 'cpu'


persistentwatcher:
  background_frame_path: "utils/backgrounds/background_pdv15.jpg"
  model_path: "models/final_best_103.pt"
  conf_threshold: 0.35  
  device: 'cpu'
  target_classes:
    - plastic-bag
    - products
    - rag
  roi: [0.5578125, 0.3472222222222222, 0.62890625, 0.41944444444444445]      
  time_threshold: 1.0
  smoothing_window: 7
  alpha: 0.8
  display_scale: 0.7
  motion_threshold: 0.1       
  disappearance_window: 10
  background_frame_index: 0
  window_size: 7
  min_area_ratio: 0.20
  min_high_frames: 6
  min_low_frames: 3
  min_immobility_duration: 1.5
  high_similarity_threshold: 0.9
  low_similarity_threshold: 0.8
  min_class_count: 3
  roi_threshold: 0.3